services:
  app:
    container_name: todo_app
    build:
      dockerfile: Docker/Django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./MyProject:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000